# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Run Python application

on:
  schedule:
    - cron:  '0 12 * * *'
# https://www.python-engineer.com/posts/run-python-github-actions/

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: execute py script
      env:
        SECRET: ${{ secrets.GMAIL_PW }}
        SECRET_GMAIL: ${{ secrets.EMAIL_ADDRESS }}
        SECRET_EMAIL: ${{ secrets.GMAIL_ADDRESS }}
        SECRET_RSS: ${{ secrets.RSS_URL }}
      run: |
        python philarchive_daily.py
